server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - PrefixPath=/
      routes:
        # =====================
        - id: useraccounts
          uri: lb://useraccounts
          predicates:
            - Path=/useraccounts/**
        # =====================
        - id: bankaccounts
          uri: lb://bankaccounts
          predicates:
            - Path=/bankaccounts/**
        # =====================
        - id: authorization
          uri: lb://authorizations
          predicates:
            - Path=/authorizations/**