server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - PrefixPath=/
      routes:
        # =====================
        - id: user
          uri: lb://user
          predicates:
            - Path=/users/**
        # =====================
#        - id: quiz
#          uri: lb://quiz
#          predicates:
#            - Path=/quizzes/**