server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - PrefixPath=/
      routes:
        # =====================
        - id: useraccount
          uri: lb://useraccount
          predicates:
            - Path=/useraccounts/**
        # =====================
        - id: bankaccount
          uri: lb://bankaccount
          predicates:
            - Path=/bankaccounts/**
        # =====================
        - id: authorization
          uri: lb://authorization
          predicates:
            - Path=/authorization/**